# Race Mapping Normalization File

import numpy as np

# Race variables normalization 
# American Indian or Alaskan Native
amer_ind_or_alaska_nat = 'American Indian or Alaskan Native'

# Asian
asian = 'Asian'

# Black or African American
black = "Black or African American"

# Caucasian / White
white = "White"

# Native Hawaiian or Other Pacific Islander
nat_haw = "Native Hawaiian or Other Pacific Islander"

# Two or More Races AKA multi-racial
multi_racial = "Multiracial"

# other
prefer_no_answer = 'Prefer not to answer'
other = 'Other'

race_mapping ={
 'Black / African American ':   black,
 'Raza negra / afroamericano ': black,
 'Black or African American':   black,
 'Black / African American Decline to answer ':black,
 'Decline to answer Black / African American ':black,
 
 'White':   white,
 'White ':  white,
 'Blanco ': white,
 'White Decline to answer ':white,
 'Blanco Prefiere no responder ':white,
 'Decline to answer White ':white,
 
 
 'Native Hawaiian / Other Pacific Islander ':nat_haw,
 'Native Hawaiian or Other Pacific Islander':nat_haw,

 'Asian':asian,
 'Asian ':asian,
  
 'American Indian / Alaska Native ':amer_ind_or_alaska_nat,
 'American Indian or Alaska Native':amer_ind_or_alaska_nat,
 'IndÃ\xadgena americano / nativo de Alaska ':amer_ind_or_alaska_nat,
 'Decline to answer American Indian / Alaska Native ':amer_ind_or_alaska_nat,
 
 'Otro / multirracial ':multi_racial,
 'Black / African American White Other / Multiracial ':multi_racial,
 'Black / African American American Indian / Alaska Native ':multi_racial,
 'Other / Multiracial ':        multi_racial,
 'Black / African American Asian ':multi_racial,
 'Other or Multi-racial':multi_racial,
 'Other / Multiracial American Indian / Alaska Native ':multi_racial,
 'Black / African American Other / Multiracial ':multi_racial,
 'Black / African American White ':multi_racial,
 'White Black / African American ':multi_racial,
 'White American Indian / Alaska Native ':multi_racial,
 'Other / Multiracial Black / African American ':multi_racial,
 'American Indian / Alaska Native Black / African American ':multi_racial,
 'Black / African American Asian Other / Multiracial ':multi_racial,
 'Native Hawaiian / Other Pacific Islander American Indian / Alaska Native ':multi_racial,
 'White Black / African American Native Hawaiian / Other Pacific Islander ':multi_racial,
 'White Black / African American Asian ':multi_racial,
 'White American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'White Asian ':multi_racial,
 'White Other / Multiracial ':multi_racial,
 'Black / African American White Asian ':multi_racial,
 'Asian American Indian / Alaska Native Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Black / African American American Indian / Alaska Native White ':multi_racial,
 'Other / Multiracial White Black / African American American Indian / Alaska Native ':multi_racial,
 'White Black / African American Asian American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'White Black / African American Other / Multiracial ':multi_racial,
 'White Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Otro / multirracial Blanco ':multi_racial,
 'American Indian / Alaska Native White Black / African American ':multi_racial,
 'Other / Multiracial White ':multi_racial,
 'American Indian / Alaska Native White ':multi_racial,
 'White Black / African American American Indian / Alaska Native ':multi_racial,
 'Asian Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Black / African American White American Indian / Alaska Native ':multi_racial,
 'White Asian Black / African American American Indian / Alaska Native Native Hawaiian / Other Pacific Islander Other / Multiracial ':multi_racial,
 'Asian Black / African American ':multi_racial,
 'Black / African American American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'Native Hawaiian / Other Pacific Islander Black / African American Other / Multiracial ':multi_racial,
 'Otro / multirracial Raza negra / afroamericano ':multi_racial,
 'Other / Multiracial White Black / African American ':multi_racial,
 'American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'Asian White ':multi_racial,
 'White Asian Decline to answer ':multi_racial,
 'Other / Multiracial Black / African American White ':multi_racial,
 'American Indian / Alaska Native Asian Black / African American ':multi_racial,
 'Decline to answer Other / Multiracial White ':multi_racial,
 'Blanco AsiÃ¡tico ':multi_racial,

 'Decline to answer ':prefer_no_answer,
 'Prefiere no responder ':prefer_no_answer,
 'Prefer not to Answer':prefer_no_answer,

 np.nan: np.nan,
 None: np.nan
}

race_mapping_host ={
 'Black / African American ':   black,
 'Raza negra / afroamericano ': black,
 'Raza negra / afroamericano':  black,
 'Black or African American':   black,
 'Black / African American':    black,
 'Black / African American Decline to answer ':black,
 'Decline to answer Black / African American ':black,
 'Black / African American\nDecline to answer':black,
 'Decline to answer\nBlack / African American':black,
 
 'White':   white,
 'White ':  white,
 'Blanco ': white,
 'Blanco':  white,
 'White Decline to answer ':white,
 'Blanco Prefiere no responder ':white,
 'Decline to answer White ':white,
 'White\nDecline to answer':white,
 'Decline to answer\nWhite':white,
 'Prefiere no responder\nBlanco':white,
 'Blanco\nPrefiere no responder':white,
 
 
 'Native Hawaiian / Other Pacific Islander ':nat_haw,
 'Native Hawaiian or Other Pacific Islander':nat_haw,
 'Native Hawaiian / Other Pacific Islander':nat_haw,
 'Nativo de Hawái / otro isleño del Pacífico':nat_haw,

 'Asian':asian,
 'Asian ':asian,
 'Asiático':asian,
  
 'American Indian / Alaska Native':amer_ind_or_alaska_nat,
 'American Indian / Alaska Native ':amer_ind_or_alaska_nat,
 'American Indian or Alaska Native':amer_ind_or_alaska_nat,
 'IndÃ\xadgena americano / nativo de Alaska ':amer_ind_or_alaska_nat,
 'Decline to answer American Indian / Alaska Native ':amer_ind_or_alaska_nat,
 'American Indian / Alaska Native\nDecline to answer':amer_ind_or_alaska_nat,
 'Decline to answer\nAmerican Indian / Alaska Native':amer_ind_or_alaska_nat,
 'Indígena americano / nativo de Alaska':amer_ind_or_alaska_nat,
 'Prefiere no responder\nIndígena americano / nativo de Alaska':amer_ind_or_alaska_nat,
 
 # American Indian/ Alaska Native & White
 'White American Indian / Alaska Native ':'American Indian/ Alaska Native & White',
 'American Indian / Alaska Native White ':'American Indian/ Alaska Native & White',
 'White\nAmerican Indian / Alaska Native':'American Indian/ Alaska Native & White',
 'American Indian / Alaska Native\nWhite':'American Indian/ Alaska Native & White',
 
 # Asian & White
 'White Asian ':'Asian & White',
 'Asian White ':'Asian & White',
 'White Asian Decline to answer ':'Asian & White',
 'White\nAsian':'Asian & White',
 'Asian\nWhite':'Asian & White',
 'White\nAsian\nDecline to answer':'Asian & White',
 'Asiático\nBlanco':'Asian & White',
 'Blanco\nAsiático':'Asian & White',

 # Black/African American & White
 'Black / African American White ':'Black/African American & White',
 'White Black / African American ':'Black/African American & White',
 'Black / African American\nWhite':'Black/African American & White',
 'White\nBlack / African American':'Black/African American & White',
 'White\nBlack / African American\nDecline to answer':'Black/African American & White',
 'Blanco\nRaza negra / afroamericano':'Black/African American & White',
 'Raza negra / afroamericano\nBlanco':'Black/African American & White',
 
 # American Indian/ Alaska Native & Black/ African American
 'American Indian / Alaska Native Black / African American ':'American Indian/ Alaska Native & Black/ African American',
 'Black / African American American Indian / Alaska Native ':'American Indian/ Alaska Native & Black/ African American',
 'Black / African American\nAmerican Indian / Alaska Native':'American Indian/ Alaska Native & Black/ African American',
 'American Indian / Alaska Native\nBlack / African American':'American Indian/ Alaska Native & Black/ African American',

 'Otro / multirracial ':multi_racial,
 'Black / African American White Other / Multiracial ':multi_racial,
 'Other / Multiracial ':        multi_racial,
 'Other / Multiracial':         multi_racial,
 'Black / African American Asian ':multi_racial,
 'Other or Multi-racial':multi_racial,
 'Other / Multiracial American Indian / Alaska Native ':multi_racial,
 'Black / African American Other / Multiracial ':multi_racial, 
 'Other / Multiracial Black / African American ':multi_racial,
 'Black / African American Asian Other / Multiracial ':multi_racial,
 'Native Hawaiian / Other Pacific Islander American Indian / Alaska Native ':multi_racial,
 'American Indian / Alaska Native\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'White Black / African American Native Hawaiian / Other Pacific Islander ':multi_racial,
 'White Black / African American Asian ':multi_racial,
 'White American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'White Other / Multiracial ':multi_racial,
 'Black / African American White Asian ':multi_racial,
 'Asian American Indian / Alaska Native Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Black / African American American Indian / Alaska Native White ':multi_racial,
 'Other / Multiracial White Black / African American American Indian / Alaska Native ':multi_racial,
 'White Black / African American Asian American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'White Black / African American Other / Multiracial ':multi_racial,
 'White Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Otro / multirracial Blanco ':multi_racial,
 'American Indian / Alaska Native White Black / African American ':multi_racial,
 'Other / Multiracial White ':multi_racial,
 'White Black / African American American Indian / Alaska Native ':multi_racial,
 'Asian Native Hawaiian / Other Pacific Islander ':multi_racial,
 'Black / African American White American Indian / Alaska Native ':multi_racial,
 'White Asian Black / African American American Indian / Alaska Native Native Hawaiian / Other Pacific Islander Other / Multiracial ':multi_racial,
 'Asian Black / African American ':multi_racial,
 'Black / African American American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'Native Hawaiian / Other Pacific Islander Black / African American Other / Multiracial ':multi_racial,
 'Otro / multirracial Raza negra / afroamericano ':multi_racial,
 'Other / Multiracial White Black / African American ':multi_racial,
 'American Indian / Alaska Native Other / Multiracial ':multi_racial,
 'American Indian / Alaska Native Asian Black / African American ':multi_racial,
 'Other / Multiracial Black / African American White ':multi_racial,
 'Decline to answer Other / Multiracial White ':multi_racial,
 'Blanco AsiÃ¡tico ':multi_racial,
  'Black / African American\nOther / Multiracial':multi_racial,
 'Black / African American\nWhite\nAsian':multi_racial,
 'White\nBlack / African American\nAmerican Indian / Alaska Native':multi_racial,
 'Black / African American\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nOther / Multiracial':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nBlack / African American':multi_racial,
 'Black / African American\nWhite\nOther / Multiracial':multi_racial,
 'White\nAsian\nOther / Multiracial':multi_racial,
 'Other / Multiracial\nBlack / African American':multi_racial,
 'White\nOther / Multiracial':multi_racial,
 'American Indian / Alaska Native\nWhite\nBlack / African American':multi_racial,
 'Black / African American\nWhite\nAmerican Indian / Alaska Native':multi_racial,
 'Other / Multiracial\nWhite':multi_racial,
 'White\nNative Hawaiian / Other Pacific Islander\nBlack / African American':multi_racial,
 'Other / Multiracial\nWhite\nBlack / African American':multi_racial,
 'White\nBlack / African American\nOther / Multiracial':multi_racial,
 'Asian\nBlack / African American':multi_racial,
 'Black / African American\nAsian':multi_racial,
 'Black / African American\nAsian\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Black / African American\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'White\nAsian\nBlack / African American':multi_racial,
 'White\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Other / Multiracial\nBlack / African American\nWhite':multi_racial,
 'Black / African American\nOther / Multiracial\nWhite':multi_racial,
 'American Indian / Alaska Native\nOther / Multiracial\nWhite':multi_racial,
 'Black / African American\nAmerican Indian / Alaska Native\nWhite':multi_racial,
 'Other / Multiracial\nDecline to answer':multi_racial,
 'American Indian / Alaska Native\nBlack / African American\nWhite':multi_racial,
 'Asian\nOther / Multiracial':multi_racial,
 'Asian\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Other / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'White\nBlack / African American\nAsian':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nWhite':multi_racial,
 'White\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nBlack / African American\nWhite\nOther / Multiracial':multi_racial,
 'White\nBlack / African American\nAsian\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'White\nBlack / African American\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'Asian\nBlack / African American\nWhite':multi_racial,
 'White\nAsian\nNative Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'Other / Multiracial\nAmerican Indian / Alaska Native\nBlack / African American':multi_racial,
 'Black / African American\nAsian\nWhite\nAmerican Indian / Alaska Native':multi_racial,
 'Asian\nAmerican Indian / Alaska Native\nWhite':multi_racial,
 'American Indian / Alaska Native\nNative Hawaiian / Other Pacific Islander\nWhite':multi_racial,
 'Black / African American\nAmerican Indian / Alaska Native\nAsian\nWhite':multi_racial,
 'Black / African American\nOther / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'White\nBlack / African American\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Black / African American\nWhite\nOther / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'American Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'White\nBlack / African American\nOther / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'Other / Multiracial\nAmerican Indian / Alaska Native\nWhite\nBlack / African American\nNative Hawaiian / Other Pacific Islander\nAsian':multi_racial,
 'Other / Multiracial\nBlack / African American\nAmerican Indian / Alaska Native\nWhite':multi_racial,
 'Black / African American\nWhite\nOther / Multiracial\nAsian':multi_racial,
 'Other / Multiracial\nAsian':multi_racial,
 'Asian\nAmerican Indian / Alaska Native\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Black / African American\nNative Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nAsian':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nBlack / African American\nOther / Multiracial':multi_racial,
 'American Indian / Alaska Native\nAsian\nBlack / African American':multi_racial,
 'Other / Multiracial\nAmerican Indian / Alaska Native\nWhite':multi_racial,
 'American Indian / Alaska Native\nBlack / African American\nOther / Multiracial':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nBlack / African American\nWhite':multi_racial,
 'Other / Multiracial\nNative Hawaiian / Other Pacific Islander\nBlack / African American':multi_racial,
 'Black / African American\nAsian\nAmerican Indian / Alaska Native':multi_racial,
 'White\nOther / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'Decline to answer\nOther / Multiracial\nWhite':multi_racial,
 'Black / African American\nOther / Multiracial\nAmerican Indian / Alaska Native\nWhite':multi_racial,
 'Other / Multiracial\nNative Hawaiian / Other Pacific Islander\nBlack / African American\nWhite\nAmerican Indian / Alaska Native':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nAsian\nBlack / African American':multi_racial,
 'Other / Multiracial\nBlack / African American\nAmerican Indian / Alaska Native':multi_racial,
 'White\nAsian\nBlack / African American\nAmerican Indian / Alaska Native\nNative Hawaiian / Other Pacific Islander\nOther / Multiracial':multi_racial,
 'Black / African American\nOther / Multiracial\nWhite\nAmerican Indian / Alaska Native':multi_racial,
 'White\nBlack / African American\nAsian\nNative Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native':multi_racial,
 'American Indian / Alaska Native\nWhite\nOther / Multiracial':multi_racial,
 'White\nAmerican Indian / Alaska Native\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'American Indian / Alaska Native\nAsian\nWhite':multi_racial,
 'White\nBlack / African American\nAsian\nAmerican Indian / Alaska Native':multi_racial,
 'Other / Multiracial\nBlack / African American\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Black / African American\nAsian\nOther / Multiracial':multi_racial,
 'Black / African American\nWhite\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'White\nAsian\nAmerican Indian / Alaska Native':multi_racial,
 'Black / African American\nWhite\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'Asian\nWhite\nOther / Multiracial\nAmerican Indian / Alaska Native':multi_racial,
 'White\nAsian\nAmerican Indian / Alaska Native\nOther / Multiracial':multi_racial,
 'White\nBlack / African American\nOther / Multiracial\nNative Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native\nAsian':multi_racial,
 'Black / African American\nNative Hawaiian / Other Pacific Islander\nWhite':multi_racial,
 'Native Hawaiian / Other Pacific Islander\nAmerican Indian / Alaska Native\nBlack / African American\nWhite':multi_racial,
 'Other / Multiracial\nWhite\nBlack / African American\nAmerican Indian / Alaska Native':multi_racial,
 'Black / African American\nAsian\nWhite':multi_racial,
 'White\nAmerican Indian / Alaska Native\nBlack / African American':multi_racial,
 'White\nAmerican Indian / Alaska Native\nDecline to answer\nOther / Multiracial':multi_racial,
 'White\nAsian\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Black / African American\nOther / Multiracial\nAsian':multi_racial,
 'Black / African American\nWhite\nOther / Multiracial\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Other / Multiracial\nAsian\nBlack / African American\nWhite':multi_racial,
 'Other / Multiracial\nWhite\nBlack / African American\nNative Hawaiian / Other Pacific Islander':multi_racial,
 'Asian\nAmerican Indian / Alaska Native':multi_racial,
 'White\nAmerican Indian / Alaska Native\nAsian':multi_racial,
 'Otro / multirracial':multi_racial,
 'Prefiere no responder\nOtro / multirracial':multi_racial,
 'Nativo de Hawái / otro isleño del Pacífico\nBlanco':multi_racial,
 'Otro / multirracial\nBlanco':multi_racial,
 'Raza negra / afroamericano\nBlanco\nAsiático\nIndígena americano / nativo de Alaska\nNativo de Hawái / otro isleño del Pacífico\nOtro / multirracial':multi_racial,
 'Otro / multirracial\nPrefiere no responder':multi_racial,
 'Asiático\nOtro / multirracial\nBlanco\nIndígena americano / nativo de Alaska\nNativo de Hawái / otro isleño del Pacífico\nRaza negra / afroamericano\nPrefiere no responder':multi_racial,
 'Blanco\nOtro / multirracial':multi_racial,
 'Otro / multirracial\nIndígena americano / nativo de Alaska':multi_racial,
 'Otro / multirracial\nRaza negra / afroamericano':multi_racial,

 'Decline to answer ':prefer_no_answer,
 'Prefiere no responder ':prefer_no_answer,
 'Prefiere no responder':prefer_no_answer,
 'Prefer not to Answer':prefer_no_answer,
 'Decline to answer':prefer_no_answer,

 np.nan: np.nan,
 None: np.nan
}